//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.13 at 09:56:55 上午 CST 
//


package org.blue.sdbx.xsd.ss;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="province">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *               &lt;enumeration value="100"/>
 *               &lt;enumeration value="200"/>
 *               &lt;enumeration value="210"/>
 *               &lt;enumeration value="220"/>
 *               &lt;enumeration value="230"/>
 *               &lt;enumeration value="240"/>
 *               &lt;enumeration value="250"/>
 *               &lt;enumeration value="270"/>
 *               &lt;enumeration value="280"/>
 *               &lt;enumeration value="290"/>
 *               &lt;enumeration value="311"/>
 *               &lt;enumeration value="351"/>
 *               &lt;enumeration value="371"/>
 *               &lt;enumeration value="431"/>
 *               &lt;enumeration value="451"/>
 *               &lt;enumeration value="471"/>
 *               &lt;enumeration value="531"/>
 *               &lt;enumeration value="551"/>
 *               &lt;enumeration value="571"/>
 *               &lt;enumeration value="591"/>
 *               &lt;enumeration value="731"/>
 *               &lt;enumeration value="771"/>
 *               &lt;enumeration value="791"/>
 *               &lt;enumeration value="851"/>
 *               &lt;enumeration value="871"/>
 *               &lt;enumeration value="891"/>
 *               &lt;enumeration value="898"/>
 *               &lt;enumeration value="931"/>
 *               &lt;enumeration value="951"/>
 *               &lt;enumeration value="971"/>
 *               &lt;enumeration value="991"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="createtime" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="sum" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="begintime" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="endtime" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="data">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="rcd" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="seq" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *                             &lt;element name="mainacc">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{}NonZeroLenString">
 *                                   &lt;maxLength value="64"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                             &lt;element name="mainid">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{}NonZeroLenString">
 *                                   &lt;maxLength value="256"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                             &lt;element name="subacc">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{}NonZeroLenString">
 *                                   &lt;maxLength value="64"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                             &lt;element name="subid">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{}NonZeroLenString">
 *                                   &lt;maxLength value="256"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                             &lt;element name="subacctype">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *                                   &lt;enumeration value="1"/>
 *                                   &lt;enumeration value="2"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                             &lt;element name="effecttime" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *                             &lt;element name="expiretime" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *                             &lt;element name="establishtime" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *                             &lt;element name="updatetime" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "type",
    "province",
    "createtime",
    "sum",
    "begintime",
    "endtime",
    "data"
})
@XmlRootElement(name = "sdbx")
public class Sdbx {

    @XmlElement(required = true)
    protected String type;
    @XmlElement(required = true)
    protected BigInteger province;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar createtime;
    @XmlElement(required = true)
    protected BigInteger sum;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar begintime;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar endtime;
    @XmlElement(required = true)
    protected Sdbx.Data data;

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the province property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getProvince() {
        return province;
    }

    /**
     * Sets the value of the province property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setProvince(BigInteger value) {
        this.province = value;
    }

    /**
     * Gets the value of the createtime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCreatetime() {
        return createtime;
    }

    /**
     * Sets the value of the createtime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCreatetime(XMLGregorianCalendar value) {
        this.createtime = value;
    }

    /**
     * Gets the value of the sum property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSum() {
        return sum;
    }

    /**
     * Sets the value of the sum property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSum(BigInteger value) {
        this.sum = value;
    }

    /**
     * Gets the value of the begintime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getBegintime() {
        return begintime;
    }

    /**
     * Sets the value of the begintime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setBegintime(XMLGregorianCalendar value) {
        this.begintime = value;
    }

    /**
     * Gets the value of the endtime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getEndtime() {
        return endtime;
    }

    /**
     * Sets the value of the endtime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setEndtime(XMLGregorianCalendar value) {
        this.endtime = value;
    }

    /**
     * Gets the value of the data property.
     * 
     * @return
     *     possible object is
     *     {@link Sdbx.Data }
     *     
     */
    public Sdbx.Data getData() {
        return data;
    }

    /**
     * Sets the value of the data property.
     * 
     * @param value
     *     allowed object is
     *     {@link Sdbx.Data }
     *     
     */
    public void setData(Sdbx.Data value) {
        this.data = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="rcd" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="seq" type="{http://www.w3.org/2001/XMLSchema}integer"/>
     *                   &lt;element name="mainacc">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{}NonZeroLenString">
     *                         &lt;maxLength value="64"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="mainid">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{}NonZeroLenString">
     *                         &lt;maxLength value="256"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="subacc">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{}NonZeroLenString">
     *                         &lt;maxLength value="64"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="subid">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{}NonZeroLenString">
     *                         &lt;maxLength value="256"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="subacctype">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
     *                         &lt;enumeration value="1"/>
     *                         &lt;enumeration value="2"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="effecttime" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
     *                   &lt;element name="expiretime" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
     *                   &lt;element name="establishtime" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
     *                   &lt;element name="updatetime" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "rcd"
    })
    public static class Data {

        protected List<Sdbx.Data.Rcd> rcd;

        /**
         * Gets the value of the rcd property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the rcd property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getRcd().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Sdbx.Data.Rcd }
         * 
         * 
         */
        public List<Sdbx.Data.Rcd> getRcd() {
            if (rcd == null) {
                rcd = new ArrayList<Sdbx.Data.Rcd>();
            }
            return this.rcd;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="seq" type="{http://www.w3.org/2001/XMLSchema}integer"/>
         *         &lt;element name="mainacc">
         *           &lt;simpleType>
         *             &lt;restriction base="{}NonZeroLenString">
         *               &lt;maxLength value="64"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="mainid">
         *           &lt;simpleType>
         *             &lt;restriction base="{}NonZeroLenString">
         *               &lt;maxLength value="256"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="subacc">
         *           &lt;simpleType>
         *             &lt;restriction base="{}NonZeroLenString">
         *               &lt;maxLength value="64"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="subid">
         *           &lt;simpleType>
         *             &lt;restriction base="{}NonZeroLenString">
         *               &lt;maxLength value="256"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="subacctype">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
         *               &lt;enumeration value="1"/>
         *               &lt;enumeration value="2"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="effecttime" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
         *         &lt;element name="expiretime" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
         *         &lt;element name="establishtime" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
         *         &lt;element name="updatetime" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "seq",
            "mainacc",
            "mainid",
            "subacc",
            "subid",
            "subacctype",
            "effecttime",
            "expiretime",
            "establishtime",
            "updatetime"
        })
        public static class Rcd {

            @XmlElement(required = true)
            protected BigInteger seq;
            @XmlElement(required = true)
            protected String mainacc;
            @XmlElement(required = true)
            protected String mainid;
            @XmlElement(required = true)
            protected String subacc;
            @XmlElement(required = true)
            protected String subid;
            @XmlElement(required = true)
            protected BigInteger subacctype;
            @XmlElement(required = true)
            @XmlSchemaType(name = "dateTime")
            protected XMLGregorianCalendar effecttime;
            @XmlElement(required = true)
            @XmlSchemaType(name = "dateTime")
            protected XMLGregorianCalendar expiretime;
            @XmlElement(required = true)
            @XmlSchemaType(name = "dateTime")
            protected XMLGregorianCalendar establishtime;
            @XmlElement(required = true)
            @XmlSchemaType(name = "dateTime")
            protected XMLGregorianCalendar updatetime;

            /**
             * Gets the value of the seq property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getSeq() {
                return seq;
            }

            /**
             * Sets the value of the seq property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setSeq(BigInteger value) {
                this.seq = value;
            }

            /**
             * Gets the value of the mainacc property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getMainacc() {
                return mainacc;
            }

            /**
             * Sets the value of the mainacc property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setMainacc(String value) {
                this.mainacc = value;
            }

            /**
             * Gets the value of the mainid property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getMainid() {
                return mainid;
            }

            /**
             * Sets the value of the mainid property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setMainid(String value) {
                this.mainid = value;
            }

            /**
             * Gets the value of the subacc property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSubacc() {
                return subacc;
            }

            /**
             * Sets the value of the subacc property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSubacc(String value) {
                this.subacc = value;
            }

            /**
             * Gets the value of the subid property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSubid() {
                return subid;
            }

            /**
             * Sets the value of the subid property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSubid(String value) {
                this.subid = value;
            }

            /**
             * Gets the value of the subacctype property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getSubacctype() {
                return subacctype;
            }

            /**
             * Sets the value of the subacctype property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setSubacctype(BigInteger value) {
                this.subacctype = value;
            }

            /**
             * Gets the value of the effecttime property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public XMLGregorianCalendar getEffecttime() {
                return effecttime;
            }

            /**
             * Sets the value of the effecttime property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public void setEffecttime(XMLGregorianCalendar value) {
                this.effecttime = value;
            }

            /**
             * Gets the value of the expiretime property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public XMLGregorianCalendar getExpiretime() {
                return expiretime;
            }

            /**
             * Sets the value of the expiretime property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public void setExpiretime(XMLGregorianCalendar value) {
                this.expiretime = value;
            }

            /**
             * Gets the value of the establishtime property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public XMLGregorianCalendar getEstablishtime() {
                return establishtime;
            }

            /**
             * Sets the value of the establishtime property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public void setEstablishtime(XMLGregorianCalendar value) {
                this.establishtime = value;
            }

            /**
             * Gets the value of the updatetime property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public XMLGregorianCalendar getUpdatetime() {
                return updatetime;
            }

            /**
             * Sets the value of the updatetime property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public void setUpdatetime(XMLGregorianCalendar value) {
                this.updatetime = value;
            }

        }

    }

}
